FROM alpine:latest


RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    && pip install awscli --upgrade --user \
    && apk --purge -v del py-pip \
    && rm -rf /var/cache/apk/*

copy process.sh /usr/share
CMD [ "sh","/usr/share/process.sh"]
